services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: nova_learn_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg-pass
      TZ: 'UTC'
    ports:
      - '25432:5432'

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: 12345678
      PGADMIN_CONFIG_WTF_CSRF_ENABLED: 'False'
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: 'False'
    ports:
      - '8080:80'
    volumes:
      - pgadmin_data:/root/.pgadmin
