services:
  nova-learn-api:
    image: nova-learn-api-local
    container_name: nova-learn-api-local
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file:
      - .env.docker
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
    command: pnpm start:dev
    networks:
      - nova-learn-network
    depends_on:
      - db
      - redis
      - maildev
      - minio
      - kafka

  db:
    extends:
      file: ./infras/postgresql.yaml
      service: postgres
    networks:
      - nova-learn-network

  redis:
    extends:
      file: ./infras/redis.yaml
      service: redis
    networks:
      - nova-learn-network

  maildev:
    extends:
      file: ./infras/maildev.yaml
      service: maildev
    networks:
      - nova-learn-network

  pgadmin:
    extends:
      file: ./infras/postgresql.yaml
      service: pgadmin
    depends_on:
      - db
    networks:
      - nova-learn-network

  minio:
    extends:
      file: ./infras/minio.yaml
      service: minio
    networks:
      - nova-learn-network

  kafka:
    extends:
      file: ./infras/kafka.yaml
      service: kafka
    networks:
      - nova-learn-network

volumes:
  postgres_data:
  pgadmin_data:
  redis_data:
  minio_data:
    driver: local
  minio_config:
    driver: local

networks:
  nova-learn-network:
    driver: bridge
