services:
  nova-up-api:
    image: nova-up-api-local
    container_name: nova-up-api-local
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file:
      - .env.docker
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
    command: pnpm start:dev
    networks:
      - nova-up-network

  db:
    image: postgres:16
    container_name: nova-up-postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: nova_up_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: 'UTC'
    ports:
      - '25432:5432'
    networks:
      - nova-up-network

  redis:
    image: redis/redis-stack:latest
    restart: always
    ports:
      - '6379:6379'
      - '8001:8001'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
    environment:
      REDIS_ARGS: '--requirepass redispass'
    networks:
      - nova-up-network

  # maildev:
  #   build:
  #     context: .
  #     dockerfile: maildev.Dockerfile
  #   ports:
  #     - ${MAIL_CLIENT_PORT}:1080
  #     - ${MAIL_PORT}:1025
  #   networks:
  #     - nova-up-network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - '18080:80'
    volumes:
      - pgadmin_data:/root/.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: 12345678
      PGADMIN_CONFIG_WTF_CSRF_ENABLED: 'False'
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: 'False'
    networks:
      - nova-up-network

volumes:
  postgres_data:
  pgadmin_data:
  redis_data:

networks:
  nova-up-network:
    driver: bridge
