apiVersion: apps/v1
kind: Deployment
metadata:
    name: dpm-account
    namespace: ns-account
spec:
    replicas: 1
    selector:
        matchLabels:
            app: app-account
    template:
        metadata:
            labels:
                app: app-account
        spec:
            restartPolicy: Always
            containers:
                - name: app-account
                  image: khoimd/account-img
                  resources:
                      requests:
                          memory: "64Mi"
                          cpu: "50m"
                      limits:
                          memory: "64Mi"
                          cpu: "100m"

                  # env:
                  #     - name: NODE_ENV
                  #       value: "production"
                  #     - name: APP_PORT
                  #       value: "3000"
                  #     - name: AUTH_FACEBOOK_JWKS_URL
                  #       valueFrom:
                  #           configMapKeyRef:
                  #               name: facebook-jkws-url
                  #               key: FACEBOOK_JWKS_URL
                  #     - name: AUTH_JWT_KEY
                  #       valueFrom:
                  #           configMapKeyRef:
                  #               name: auth-jwt-key
                  #               key: AUTH_JWT_KEY
                  #     - name: AUTH_FACEBOOK_DEBUG_TOKEN_URL
                  #       valueFrom:
                  #           configMapKeyRef:
                  #               name: facebook-debug-token-url
                  #               key: FACEBOOK_DEBUG_TOKEN_URL
                  #     - name: AUTH_FACEBOOK_GET_ACCESS_TOKEN_URL
                  #       valueFrom:
                  #           configMapKeyRef:
                  #               name: facebook-access-token-url
                  #               key: FACEBOOK_ACCESS_TOKEN_URL
                  #     - name: ADDRESS_SERVICE_URL
                  #       value: "http://address-service-srv.dev-mochimalls-address.svc.cluster.local:3001"
                  #     - name: FAVORITE_SERVICE_URL
                  #       value: "http://favorites-service-srv.dev-mochimalls-favorite.svc.cluster.local:3005"
                  #     - name: UTILITY_SERVICE_URL
                  #       value: "http://utility-service-srv.dev-mochimalls-utility.svc.cluster.local:3003"
                  #     - name: SUBSCRIPTION_SERVICE_URL
                  #       value: "http://subscriptions-service-srv.dev-mochimalls-subscription.svc.cluster.local:3002"
                  #     - name: AGREEMENT_SERVICE_URL
                  #       value: "http://agreements-service-srv.dev-mochimalls-agreement.svc.cluster.local:3006"
                  #     - name: AUTH_JWT_SECRET
                  #       valueFrom:
                  #           secretKeyRef:
                  #               name: auth-jwt-secret
                  #               key: AUTH_JWT_SECRET
                  #     - name: AUTH_JWT_TOKEN_EXPIRES_IN
                  #       value: "1d"
                  #     - name: AUTH_REFRESH_SECRET
                  #       valueFrom:
                  #           secretKeyRef:
                  #               name: auth-refresh-secret
                  #               key: AUTH_REFRESH_SECRET
                  #     - name: AUTH_REFRESH_TOKEN_EXPIRES_IN
                  #       value: "30d"
                  #     - name: AUTH_GOOGLE_CLIENT_ID
                  #       valueFrom:
                  #           secretKeyRef:
                  #               name: auth-google-client-id
                  #               key: AUTH_GOOGLE_CLIENT_ID
                  #     - name: AUTH_GOOGLE_CLIENT_SECRET
                  #       valueFrom:
                  #           secretKeyRef:
                  #               name: auth-google-client-secret
                  #               key: AUTH_GOOGLE_CLIENT_SECRET
                  #     - name: AUTH_FACEBOOK_APP_ID
                  #       valueFrom:
                  #           secretKeyRef:
                  #               name: auth-facebook-app-id
                  #               key: AUTH_FACEBOOK_APP_ID
                  #     - name: AUTH_FACEBOOK_CLIENT_ID
                  #       valueFrom:
                  #           secretKeyRef:
                  #               name: auth-facebook-client-id
                  #               key: AUTH_FACEBOOK_CLIENT_ID
                  #     - name: AUTH_FACEBOOK_CLIENT_SECRET
                  #       valueFrom:
                  #           secretKeyRef:
                  #               name: auth-facebook-client-secret
                  #               key: AUTH_FACEBOOK_CLIENT_SECRET
                  #     - name: DATABASE_TYPE
                  #       value: "postgres"
                  #     - name: DATABASE_HOST
                  #       valueFrom:
                  #           secretKeyRef:
                  #               name: user-database-host
                  #               key: USER_DATABASE_HOST
                  #     - name: DATABASE_PORT
                  #       valueFrom:
                  #           secretKeyRef:
                  #               name: user-database-port
                  #               key: USER_DATABASE_PORT
                  #     - name: DATABASE_USERNAME
                  #       valueFrom:
                  #           secretKeyRef:
                  #               name: user-database-username
                  #               key: USER_DATABASE_USERNAME
                  #     - name: DATABASE_PASSWORD
                  #       valueFrom:
                  #           secretKeyRef:
                  #               name: user-database-password
                  #               key: USER_DATABASE_PASSWORD
                  #     - name: DATABASE_NAME
                  #       valueFrom:
                  #           secretKeyRef:
                  #               name: user-database-name
                  #               key: USER_DATABASE_NAME
---
apiVersion: v1
kind: Service
metadata:
    name: ci-account
    namespace: ns-account
spec:
    type: ClusterIP
    selector:
        app: app-account
    ports:
        - name: http
          protocol: TCP
          port: 3000
          targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
    name: external-ci-account
    namespace: ns-ingress
    annotations:
        cloud.google.com/backend-config: '{"default": "health-check-backend-config"}'
spec:
    type: ExternalName
    externalName: ci-account.ns-account.svc.cluster.local
    ports:
        - name: app-account
          protocol: TCP
          port: 3000
