export enum Entity {
  MEDIA = 'media',
  POST = 'post',
  PREFERENCE = 'preference',
  PERMISSION = 'permission',
  ROLE = 'role',
  USER = 'user',
  INSTRUCTOR = 'instructor',
  COURSE = 'course',
  ENROLLED_COURSE = 'enrolled-course',
  CATEGORY = 'category',
  CATEGORY_TRANSLATION = 'category-translation',
  LECTURE = 'lecture',
  CERTIFICATES = 'certificate',
  LECTURE_VIDEO = 'lecture-video',
  LECTURE_RESOURCE = 'resource',
  USER_LESSON_PROGRESS = 'user-course-progress',
  LECTURE_COMMENT = 'lecture-comment',
  FAVORITE_COURSE = 'favorite_courses',
}
