export enum Permission {
  HOME = 'read:home',
  CREATE_USER = 'create:user',
  WRITE_USER = 'write:user',
  WRITE_ROLE = 'write:role',
  READ_ROLE = 'read:role',
  WRITE_CATEGORY = 'write:category',
  DELETE_CATEGORY = 'delete:category',
  WRITE_COURSE = 'write:course',
  READ_COURSE = 'read:course',
  WRITE_SECTION = 'write:section',
  WRITE_COURSE_ITEM = 'write:course_item',
  READ_COURSE_ITEM = 'read:course_item',
  READ_ORDER = 'read:order',
  WRITE_ACCOUNT = 'write:account',
  READ_ACCOUNT = 'read:account',
  READ_PAYOUT = 'read:payout',
  WRITE_PAYOUT = 'write:payout',
  WRITE_COUPON = 'write:coupon',
  READ_REPORT = 'read:report',
}

export enum PermissionGroup {
  USER = 'user',
  ROLE = 'role',
  CATEGORY = 'category',
  COURSE = 'course',
  SECTION = 'section',
  COURSE_ITEM = 'course_item',
  ACCOUNT = 'account',
  PAYOUT = 'payout',
  COUPON = 'coupon',
  BAN = 'ban',
}
